require_relative './resources/additional_object'
require_relative './resources/agri_work_plan_application_mix_item'
require_relative './resources/agri_work_plan'
require_relative './resources/agro_operation'
require_relative './resources/application_mix_item'
require_relative './resources/avatar'
require_relative './resources/chemical'
require_relative './resources/crop'
require_relative './resources/fertilizer'
require_relative './resources/field_group'
require_relative './resources/field'
require_relative './resources/field_scout_report'
require_relative './resources/field_scout_report_threat_mapping_item'
require_relative './resources/field_shape'
require_relative './resources/group_folder'
require_relative './resources/harvest_weighing'
require_relative './resources/historical_value'
require_relative './resources/history_item'
require_relative './resources/implement'
require_relative './resources/machine_group'
require_relative './resources/machine'
require_relative './resources/machine_task_agro_operation_mapping_item'
require_relative './resources/machine_task'
require_relative './resources/note'
require_relative './resources/plant_threat'
require_relative './resources/satellite_image'
require_relative './resources/seed'
require_relative './resources/user'
require_relative './resources/user_role'
require_relative './resources/user_role_assignment'
require_relative './resources/user_role_permission'

module Cropio
  module Resources
  end
end
